name: Build Vue.js Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Change working directory
        run: cd ./portfolio/

      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio

      - name: Build project
        run: npm run build
        working-directory: ./portfolio

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./portfolio/dist/
